version: '3.4'

services:
  backendtemplate:
    image: backendtemplate
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5500:5500
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
